name: Releases
on:
  push:
    branches:
      - main

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      skip-publish: ${{ steps.bumpr.outputs.skip }}
      next_version: ${{ steps.bumpr.outputs.next_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version
        uses: haya14busa/action-bumpr@v1
        id: bumpr
        with:
          default_bump_level: ${{ inputs.default-bump-level }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  prep-matrix:
    name: Prep Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={'include':${{ inputs.build-paths }}}" >> $GITHUB_OUTPUT
