name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          npm install -g conventional-recommended-bump conventional-changelog-angular

      - name: Determine version bump
        id: bump_version
        run: |
          VERSION=$(npx conventional-recommended-bump -p angular)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Bump version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm version $VERSION -m "chore(release): %s"

      - name: Get the new version
        id: get_version
        run: echo "new_version=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Push changes and tags
        run: |
          git push --follow-tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          release_name: Release ${{ steps.get_version.outputs.new_version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
