name: Auto Version Bump and Tagging

on:
  push:
    branches:
      - main

jobs:
  version-bump-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Run git-cliff
        run: git cliff

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Determine Version Bump
        id: version_bump
        run: |
          # Determine the new version based on the changelog
          NEW_VERSION=$(git cliff --new-tag)
          echo "New Version: $NEW_VERSION"
          
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Tag New Version
        run: |
          NEW_VERSION=${{ steps.version_bump.outputs.new_version }}
          git tag "$NEW_VERSION" HEAD
          git push origin "$NEW_VERSION"
      
      - name: Print New Version
        run: echo "New version tagged: ${{ steps.version_bump.outputs.new_version }}"
