name: Auto Version Bump and Tagging

on:
  push:
    branches:
      - main

jobs:
  version-bump-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up GitCliff
        uses: gitcliff/action-git-cliff@v2
        id: cliff
        
      - name: Determine Version Bump
        run: |
          VERSION_BUMP=$(echo "${{ steps.cliff.outputs.version }}" | cut -d' ' -f2)
          echo "Version Bump: $VERSION_BUMP"
          
          # Assuming the output format from GitCliff is "git cliff vX.Y.Z", extract the version number
          NEW_VERSION=$(echo "$VERSION_BUMP" | grep -oP 'v\K\d+\.\d+\.\d+')
          
          echo "New Version: $NEW_VERSION"
          
          # Create a new tag with the determined version
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag "$NEW_VERSION" HEAD
          
          # Push the new tag to the remote repository
          git push origin "$NEW_VERSION"

      - name: Print New Version
        run: echo "New version tagged: ${{ steps.cliff.outputs.version }}"
