name: Releases
on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grant write permissions to the GITHUB_TOKEN   

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        uses: huggingface/semver-release-action@latest
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
