name: Tag Latest Version

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  tag-latest-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: path/to/repo/dir  # Checkout to a specific directory

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: someCustomTagName
          description: Description for the tag
          force-branch: true
          git-directory: path/to/repo/dir  # Directory to use when executing git commands

      - name: Push tag to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push origin --tags
        working-directory: path/to/repo/dir  # Ensure we're in the correct directory
