name: Cargo Semver Bump

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the main branch

jobs:
  build-and-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # fetch-depth 0 will check out all the commits and tags needed for the bumper
          fetch-depth: 0

      - id: bumper
        uses: tomerfi/version-bumper-action@2.0.1

      # Assuming previous tag was 1.2.4 and feat-type commits were made, this will print 1.3.0.
      - name: Print next version
        run: echo ${{ steps.bumper.outputs.next }}
