name: Automated Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --output CHANGELOG.md

      - name: Read current version
        id: current_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bumpr
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: patch
          dry_run: false

      - name: Update VERSION file
        if: steps.bumpr.outputs.new_version != ''
        run: echo "${{ steps.bumpr.outputs.new_version }}" > VERSION

      - name: Commit changes
        if: steps.bumpr.outputs.new_version != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md VERSION
          git commit -m "Bump version to ${{ steps.bumpr.outputs.new_version }} and update changelog"

      - name: Push changes
        if: steps.bumpr.outputs.new_version != ''
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create Release
        if: steps.bumpr.outputs.new_version != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bumpr.outputs.new_version }}
          name: Release ${{ steps.bumpr.outputs.new_version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
