name: Main

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Latest Tag
        id: get-tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag.outputs.tag }} # Corrected line
          release_name: Release ${{ steps.get-tag.outputs.tag }}
          draft: false
          prerelease: false
